version: '3.9'

services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-php-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./carrental:/var/www/html
    depends_on:
      - mysql
    environment:
      VIRTUAL_HOST: sabaricars.zapto.org
      CERTBOT_EMAIL: vasansabari608@gmail.com
    restart: always

  mysql:
    image: sabari88389/my-mysql:v1
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always

volumes:
  mysql_data:
